// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaP_API.Data;

namespace PaP_APIr.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20211101193845_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("PaP_API.Models.Ponto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PontoDois")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PontoQuatro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PontoTres")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PontoUm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Pontos");
                });
#pragma warning restore 612, 618
        }
    }
}
